# Dependencies
markdown:         redcarpet
highlighter:      rouge
# 在这里配置redcarpet的扩展选项，打开tables
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            留下点折腾的痕迹
tagline:          'idiotfan'
description:      'A product designer, not fulfilled with only sketching, but also implementing ideas.'
description-v1:   ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'idiotfan Wang'
  url:            idiotfan.github.io

paginate:         5

# Custom vars
version:          0.1.1

github:
  repo:           https://github.com/poole/hyde

gems:
  - jekyll-paginate
  - jekyll-gist

